set timeout -1
cd ../../
spawn python3 setup.py test

expect "/var/lib/ca_manager/private/root:"

send -- "root\r"

expect "/var/lib/ca_manager/private/root:"

send -- "root\r"

expect "/var/lib/ca_manager/private/root:"

send -- "root\r"

expect ":"

send -- "\r"

expect ":"

send -- "\r"

expect ":"

send -- "\r"

expect ":"

send -- "\r"

expect ":"

send -- "\r"

expect ":"

send -- "root\r"

expect ":"

send -- "\r"




expect "/var/lib/ca_manager/private/int:"

send -- "root\r"
expect "/var/lib/ca_manager/private/int:"

send -- "root\r"

expect "/var/lib/ca_manager/private/int:"

send -- "root\r"

expect ":"

send -- "\r"

expect ":"

send -- "\r"

expect ":"

send -- "\r"

expect ":"

send -- "\r"

expect ":"

send -- "\r"

expect ":"

send -- "int\r"

expect ":"

send -- "\r"



send -- "yes\r"

expect "/var/lib/ca_manager/private/root:"

send -- "root\r"



send -- "yes\r"

expect "/var/lib/ca_manager/private/int:"

send -- "root\r"

expect eof
